const MessageType = {
  ERROR: 'e',
  PING_PONG: 'pp',
  INITIALIZATION: 'i',
  AGGREGATED_ORDER_BOOK_UPDATE: 'aobu',
  ASSET_PAIRS_CONFIG_UPDATE: 'apcu',
  ASSET_PAIR_CONFIG_UPDATE: 'apiu',
  ADDRESS_UPDATE: 'au',
  ISOLATED_ADDRESS_UPDATE: 'iau',
  CFD_ADDRESS_UPDATE: 'auf',
  ISOLATED_CFD_ADDRESS_UPDATE: 'iauf',
  FUTURES_TRADE_INFO_UPDATE: 'fti',
  UNSUBSCRIPTION_DONE: 'ud',
} as const;

export default MessageType;
