const SubscriptionType = {
  ASSET_PAIRS_CONFIG_UPDATES_SUBSCRIBE: 'apcus',
  ASSET_PAIR_CONFIG_UPDATES_SUBSCRIBE: 'apius',
  ADDRESS_UPDATES_SUBSCRIBE: 'aus',
  ISOLATED_ADDRESS_UPDATES_SUBSCRIBE: 'iaus',
  AGGREGATED_ORDER_BOOK_UPDATES_SUBSCRIBE: 'aobus',
  CFD_ADDRESS_UPDATES_SUBSCRIBE: 'ausf',
  ISOLATED_CFD_ADDRESS_UPDATES_SUBSCRIBE: 'iausf',
  FUTURES_TRADE_INFO_SUBSCRIBE: 'fts',
  FUTURES_TRADES_STREAM_SUBSCRIBE: 'ftss'
} as const;

export default SubscriptionType;
